### ISSUE TITLE
Pre-presentation checklist

### ISSUE THREAD

**Issue by Rio517** [Rio517/fizzbuzz_react_cuba_example#1]
- [x] errors component shouldn't be visible until their is an error
- [x] Display should be more interesting than a JSON string.
- [x] Add test coverage - would be interesting to get to know https://github.com/djanowski/cutest, but I'm leaning towards skipping this for the sake of time.
- [ ] Dockerize
